package soal03;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.InterruptedIOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GUI_mhs extends javax.swing.JFrame {

    private DefaultTableModel model;
    public static final int SERVICE_PORT = 13;
//    public static final int BUFSIZE = 256;
    //List<Mahasiswa> mhs = new ArrayList<Mahasiswa>();

    /** Creates new form GUI_mahasiswa */
    public GUI_mhs() {
        try {
            initComponents();
            tampil_data();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_mhs.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        field_nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        field_nim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        field_asal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        field_kelas = new javax.swing.JTextField();
        tombol_tambah = new javax.swing.JButton();
        tombol_ubah = new javax.swing.JButton();
        tombol_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tombol_tampil = new javax.swing.JButton();
        tombol_exit = new javax.swing.JButton();
        tombol_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("NIM");

        jLabel3.setText("Asal");

        jLabel4.setText("Kelas");

        tombol_tambah.setText("Tambah");
        tombol_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_tambahActionPerformed(evt);
            }
        });

        tombol_ubah.setText("Ubah");
        tombol_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_ubahActionPerformed(evt);
            }
        });

        tombol_hapus.setText("Hapus");
        tombol_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_hapusActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Data Mahasiswa"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(51, 255, 51));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tombol_tampil.setText("Tampilkan Semua");
        tombol_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_tampilActionPerformed(evt);
            }
        });

        tombol_exit.setText("Keluar");
        tombol_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_exitActionPerformed(evt);
            }
        });

        tombol_reset.setText("Reset");
        tombol_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_asal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tombol_reset))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tombol_tampil)
                        .addGap(18, 18, 18)
                        .addComponent(tombol_tambah)
                        .addGap(18, 18, 18)
                        .addComponent(tombol_ubah)
                        .addGap(18, 18, 18)
                        .addComponent(tombol_hapus)
                        .addGap(18, 18, 18)
                        .addComponent(tombol_exit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(field_nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(field_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(field_asal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(field_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombol_tampil)
                    .addComponent(tombol_tambah)
                    .addComponent(tombol_ubah)
                    .addComponent(tombol_hapus)
                    .addComponent(tombol_exit)
                    .addComponent(tombol_reset))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-773)/2, (screenSize.height-298)/2, 773, 298);
    }// </editor-fold>//GEN-END:initComponents

    private void tombol_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_tampilActionPerformed
        try {
            // TODO add your handling code here:
            tampil_data();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_mhs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombol_tampilActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        try {
            // TODO add your handling code here:
            SerializationDemo demo = new SerializationDemo();
            List<Mahasiswa> newList = demo.deserialize("participantData.txt");

            int i = jTable1.getSelectedRow(); // mulai index 0

            int nim_e = newList.get(i).getNim();
            String nim_eDadiString = Integer.toString(nim_e);
            String nama_e = newList.get(i).getNama();
            String asal_e = newList.get(i).getAsal();
            String kelas_e = newList.get(i).getKelas();

            field_nim.setText(nim_eDadiString);
            field_nama.setText(nama_e);
            field_asal.setText(asal_e);
            field_kelas.setText(kelas_e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_mhs.class.getName()).log(Level.SEVERE, null, ex);
        }



    }//GEN-LAST:event_jTable1MouseClicked

    private void tombol_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_ubahActionPerformed
        try {
            String hostname = "localhost";
            Socket daytime = new Socket(hostname, SERVICE_PORT);
            System.out.println("Connection established");
            daytime.setSoTimeout(2000);

            int str = jTable1.getSelectedRow();



            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            String nim = field_nim.getText();
            String nama = field_nama.getText();
            String asal = field_asal.getText();
            String kelas = field_kelas.getText();


            System.out.println("Data yang diinputkan : " + nim + "," + nama + "," + asal + "," + kelas + "," + str);
            OutputStream os = daytime.getOutputStream();
            PrintStream ps = new PrintStream(os);
            ps.println(nim + "," + nama + "," + asal + "," + kelas + "," + str);
            //BufferedReader brl = new BufferedReader(new InputStreamReader(daytime.getInputStream()));
            //System.out.println("Result\t : " + brl.readLine());

            System.out.println("");
            os.flush();
            os.close();
            daytime.close();
            reset_text();
            JOptionPane.showMessageDialog(null, "Data Sudah Diubah ");
            tampil_data();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_mhs.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnknownHostException ex) {
            Logger.getLogger(GUI_mhs.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GUI_mhs.class.getName()).log(Level.SEVERE, null, ex);
        }





    }//GEN-LAST:event_tombol_ubahActionPerformed

    private void tombol_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_hapusActionPerformed
        try {
            String hostname = "localhost";
            Socket daytime = new Socket(hostname, SERVICE_PORT);
            System.out.println("Connection established");
            daytime.setSoTimeout(2000);


            //JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Menghapus data ini ?", "Warning", 2);
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

            int pilih = jTable1.getSelectedRow();

            System.out.println("Data yang diinputkan : " + pilih);
            OutputStream os = daytime.getOutputStream();
            PrintStream ps = new PrintStream(os);
            ps.println(pilih);
            //BufferedReader brl = new BufferedReader(new InputStreamReader(daytime.getInputStream()));
            //System.out.println("Result\t : " + brl.readLine());

            System.out.println("");
            os.flush();
            os.close();
            daytime.close();
            reset_text();
            JOptionPane.showMessageDialog(null, "Data berhasil Dihapus");
            tampil_data();



        } catch (IOException ex) {
            Logger.getLogger(GUI_mhs.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_mhs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombol_hapusActionPerformed

    private void tombol_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_tambahActionPerformed

        try {
            String hostname = "localhost";
            Socket daytime = new Socket(hostname, SERVICE_PORT);
            System.out.println("Connection established");
            daytime.setSoTimeout(2000);


            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            String nim = field_nim.getText();
            String nama = field_nama.getText();
            String asal = field_asal.getText();
            String kelas = field_kelas.getText();


            System.out.println("Data yang diinputkan : " + nim + "," + nama + "," + asal + "," + kelas);
            OutputStream os = daytime.getOutputStream();
            PrintStream ps = new PrintStream(os);
            ps.println(nim + "," + nama + "," + asal + "," + kelas);
            //BufferedReader brl = new BufferedReader(new InputStreamReader(daytime.getInputStream()));
            //System.out.println("Result\t : " + brl.readLine());

            System.out.println("");
            os.flush();
            os.close();
            daytime.close();
            reset_text();

            JOptionPane.showMessageDialog(null, "Data Sudah Ditambahkan ");
            tampil_data();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_mhs.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnknownHostException ex) {
            Logger.getLogger(GUI_mhs.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GUI_mhs.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_tombol_tambahActionPerformed

    private void tombol_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_tombol_exitActionPerformed

    private void tombol_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_resetActionPerformed
        // TODO add your handling code here:
        reset_text();
}//GEN-LAST:event_tombol_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI_mhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field_asal;
    private javax.swing.JTextField field_kelas;
    private javax.swing.JTextField field_nama;
    private javax.swing.JTextField field_nim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton tombol_exit;
    private javax.swing.JButton tombol_hapus;
    private javax.swing.JButton tombol_reset;
    private javax.swing.JButton tombol_tambah;
    private javax.swing.JButton tombol_tampil;
    private javax.swing.JButton tombol_ubah;
    // End of variables declaration//GEN-END:variables

    private void tampil_data() throws ClassNotFoundException {

        SerializationDemo demo = new SerializationDemo();
        List<Mahasiswa> newList = demo.deserialize("participantData.txt");

        Object[] baris = {"Data Mahasiswa"};
        model =
                new DefaultTableModel(null, baris);
        jTable1.setModel(model);
        int row = jTable1.getRowCount();
        for (int a = 0; a <
                row; a++) {
            model.removeRow(0);
        }

        for (int i = 0; i <
                newList.size(); i++) {

            Object[] data = {newList.get(i)};
            model.addRow(data);
        }

    }

    public void reset_text() {
        field_nim.setText("");
        field_nama.setText("");
        field_asal.setText("");
        field_kelas.setText("");
    }
}
